services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./backend:/var/www/html:cached
      - storage_data:/var/www/html/storage
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - appnet
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      CORS_ALLOWED_ORIGINS: "http://localhost:3000"
      DB_CONNECTION: pgsql
      DATABASE_URL: postgres://app:secret@db:5432/app?sslmode=disable
      FILESYSTEM_DISK: local
      SESSION_DRIVER: array

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  db_test:
    image: postgres:16
    container_name: db_test
    restart: always
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"  # Different host port
    tmpfs:
      - /var/lib/postgresql/data  # In-memory, gets wiped
    networks:
      - appnet

volumes:
  db_data:
  storage_data:

networks:
  appnet:
    driver: bridge
