services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./backend:/var/www/html
      - vendor_data:/var/www/html/vendor
      - storage_data:/var/www/html/storage/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - appnet
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: secret
      FILESYSTEM_DISK: local

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  db_data:
  storage_data:
  vendor_data:

networks:
  appnet:
    driver: bridge
