FROM php:8.3-fpm

RUN apt-get update && \
    apt-get install -y git unzip libpq-dev libzip-dev && \
    docker-php-ext-install pdo pdo_pgsql pgsql zip && \
    pecl install xdebug && \
    docker-php-ext-enable xdebug && \
    rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY docker /docker
COPY docker/uploads.ini /usr/local/etc/php/conf.d/
RUN chmod +x /docker/*.sh

WORKDIR /var/www/html

COPY composer.json composer.lock ./
RUN composer install --no-interaction --no-scripts --no-progress

COPY . .

EXPOSE 8000

ENTRYPOINT ["/docker/init.sh"]
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
